version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    env_file:
      - .env
    # Run a command against the development stage of the image
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DATABASE}?schema=public
    command: npm run start:dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - music-app
  postgres:
    env_file: '.env'
    container_name: nest-postgres
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - music-app
  # pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: pgadmin4_container
  #  restart: always
  #  ports:
  #    - "5050:80"
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #    PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  docker-nest-postgres:
networks:
  music-app: