version: "3.9"
services:
  nest-api:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - /app/node_modules
      - .:/app
    env_file:
      - .env
    # Run a command against the development stage of the image
   command: npm run start:dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - music-web-app
  db:
    env_file: '.env'
    container_name: nest-postgres
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    volumes:
      - /var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - music-web-app

networks:
  music-web-app: